### ISSUE TITLE
Incompatible with webpack v5 cacheDirectory 

### ISSUE THREAD

**Issue by gita-codaio** [postcss/autoprefixer#1389] opened 2021-01-21 04:18 UTC
Hi! Whenever I set `cache: { type: 'filesystem', cacheDirectory: './cache', },` I get a module warning.. 
```
2021-01-20-07:48:38 3|admin-webpack   | ModuleWarning [Warning: Warning
2021-01-20-07:48:38 3|admin-webpack   | (45:3) Replace fill-available to stretch, because spec had been changed] undefined
``` 
I believe it comes from autoprefixer. I tried debugging but I don't see fill-available within the code? 
Here is webpack issue I closed with more information https://github.com/webpack/webpack/issues/12458
Please let me know if there is another way I can debug/tips to get it working. Thank you!

Webpack Version: 5.15.0
Node Version: 14.15.4

**Comment by ai** [comment] 2021-01-21 12:43
Very strange. Cache option should not affect warnings.

Can you open Autoprefixer sources in `node_modules`, going the warning text by text search and debug the block by `console.log` or debugger?

**Comment by gita-v** [comment] 2021-01-21 16:31
Yes, can do later today -- will let you know

**Comment by zlk89** [comment] 2021-02-05 21:53
any update on this? we are also seeing this issue

**Comment by gita-v** [comment] 2021-02-05 22:57
I tried debugging and am not sure how it is picking up the `fill-available` but in the logs it is definitely getting picked up from somewhere. @ai If I create reproducible repo could you take a look?

**Comment by ai** [comment] 2021-02-05 22:58
Yeap, reproducible repo can be helpful

**Comment by ai** [comment] 2021-07-17 11:02
Closing since there was no answers

**Closed by ai** 2021-07-17 11:02 UTC
