### ISSUE TITLE
Browsers.parse takes 70% of the autoprefixer time

### ISSUE THREAD

**Issue by Knagis** [postcss/autoprefixer#1256] opened 2019-10-15 09:41 UTC
We use autoprefixer with a single .browserslistrc file in root. However, looking at profile trace for our webpack build, it shows that autoprefixer keeps reloading the file every time postcss plugin triggers. Overall it is not as much - 5 seconds total (out of 1 minute build) but for autoprefixer on its own browser list parsing takes >70% of the time.

![image](https://user-images.githubusercontent.com/8700285/66820000-8fc13b00-ef48-11e9-9df1-de45b56ed23c.png)

**Comment by ai** [comment] 2019-10-15 13:06
Are we talking about single Autoprefixer run or on processing multiple files?

Browserslist has an in-memory cache for config lookup https://github.com/browserslist/browserslist/blob/c806b2441179b15cee6eb6a783e754be6b332d20/node.js#L241-L244

**Comment by Knagis** [comment] 2019-10-15 14:29
Looking at the cache code it seems to cache based on CSS file path. We have files in many folders - but all resolve to the same browser list file.

**Comment by ai** [comment] 2019-10-17 10:24
Cache should be based on folder path.

The problem is that you can put `.browserslistrc` to any folder to override global Browserslist config.

But I have an idea how to speed this search a little.

**Comment by ai** [comment] 2019-10-17 12:48
Hope it improved Browserslist caching https://github.com/browserslist/browserslist/commit/86caf2b12d6be96af4919b711a4233c257814ebf

**Comment by ai** [comment] 2019-10-17 13:06
Can you try to update Browserslist to 4.7.1 (double check that you updated all version by `npm ls`) and check performance again?

**Comment by Knagis** [comment] 2019-10-22 08:30
With 4.7.1 profiler still shows the same distribution.

The change seems to store the parsed config for each parent folder, however reading the cache only looks at the current one. If CSS files are all in leaf folders, then the change didn't provide any improvement.

**Comment by ai** [comment] 2019-10-22 08:32
> however reading the cache only looks at the current one

Oops, I forgot about it. I will try to fix it today.

**Comment by Knagis** [comment] 2019-10-22 08:32
I will try the change and if it works, send a PR

**Comment by Knagis** [comment] 2019-10-22 08:45
The PR improves the situation, now it is 60%, instead of 70%.

Still the `resolve`/`sort` part repeats on every file - perhaps there is something that can be also cached now that config file will properly be reused.

**Comment by ai** [comment] 2019-10-22 14:42
A small optimization for `sort` https://github.com/browserslist/browserslist/commit/84227e2ac74db09307d8d6b7f261bcf3ac86549b

**Comment by ai** [comment] 2019-10-22 14:54
Can you try this commit? I added cache for `resolve` and `sort` https://github.com/browserslist/browserslist/commit/2fee1e4d7b1bae0214bbbef10d04087a2785dfd3

**Comment by Knagis** [comment] 2019-10-22 18:54
I will try it out tomorrow.

**Comment by Knagis** [comment] 2019-10-23 17:21
Looks much better. 
![image](https://user-images.githubusercontent.com/8700285/67417985-a283e180-f5d2-11e9-879a-e364c9acccf1.png)

**Comment by ai** [comment] 2019-10-24 06:52
Released in Browserslist 4.7.2.

**Closed** 2019-10-24 07:13 UTC
Labels: refactoring
