### ISSUE TITLE
no such file or directory?

### ISSUE THREAD

**Issue by vadimyer** [postcss/autoprefixer#529] opened 2015-09-28 12:12 UTC
Hey,
Strange issue, given how the readme states I issued the following command:
postcss --use autoprefixer *.css -d c:\Projects\Project\dist
Gave me an error:
```
{ [Error: ENOENT: no such file or directory, open 'c:\Projects\Project\src\css\*.css']
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'c:\\Projects\\Project\\src\\css\\*.css' }
```
Win 10 x64, nodejs 4.0.0 here.

**Comment by ben-eb** [comment] 2015-09-28 12:18
Looks like the path to your CSS is incorrect. Can you please verify?

ENOENT is thrown by node when a file/directory doesn't exist.

**Comment by TrySound** [comment] 2015-09-28 12:19
@ben-eb Looks like somehow glob is not expanded.

**Comment by ben-eb** [comment] 2015-09-28 12:22
Looks like a duplicate of https://github.com/code42day/postcss-cli/issues/23, closing.

**Closed by ben-eb** 2015-09-28 12:22 UTC
