### ISSUE TITLE
[css-grid] custom-ident in grid-template aren't being translate for IE

### ISSUE THREAD

**Issue by Ian-Y** [postcss/autoprefixer#1198] opened 2019-03-02 06:59 UTC
This is the original CSS code:

	.container {
		display: grid;
		grid-template-columns: [content] 2fr [sidebar] 1fr;
	}

	.content {
		grid-column: content;
	}

And this is the translated result:

	.container {
		display: -ms-grid;
		display: grid;
		-ms-grid-columns: [content] 2fr [sidebar] 1fr;
		grid-template-columns: [content] 2fr [sidebar] 1fr;
	}

	.content {
		grid-column: content;
	}

As you can see, the custom-idents (`content` and `sidebar`) don't seem to be translated for IE. When you test the code, the content is missing in IE.

Here is the HTML code used in the test:

	<div class="container" style="height: 500px">
		<div class="content" style="background: lime">
			Content Content Content Content Content Content.
		</div>
		<div class="sidebar" style="background: orange">
			Sidebar Sidebar Sidebar Sidebar Sidebar Sidebar.
		</div>
	</div>

**Comment by Dan503** [comment] 2019-03-02 07:03
Duplicate of #1020.

Autoprefixer currently doesn't support named lines.

**Comment by ai** [comment] 2019-03-02 08:01
Do we show a warning about lack of support?

**Comment by Dan503** [comment] 2019-03-04 04:17
I don't think we do. The easiest way to detect if line names are being used is detecting if an open square bracket (`[`) has been used in the `grid-template-*` property.

**Comment by Dan503** [comment] 2019-03-04 04:20
If a warning is to be produced, it should direct people to try and use `grid-template-areas` instead.

**Comment by ai** [comment] 2019-03-04 14:47
@Dan503 I will add a code. Can I ask you to write a proper warning message?

**Comment by Dan503** [comment] 2019-03-04 21:55
This should work. 

> Autoprefixer currently does not support line names. Try using grid-template-areas instead.

**Comment by ai** [comment] 2019-03-05 00:41
Warning was added b54ea06

**Closed by ai** 2019-03-05 00:41 UTC
