### ISSUE TITLE
Placeholder shown

### ISSUE THREAD

**Issue by StepFlow** [postcss/autoprefixer#1356] opened 2020-09-08 03:17 UTC
Using v9.7.6, browserslist: last 2 versions

This code with pseudo-class ':placeholder-shown' usage
```css
.SiteForm__input:not(:placeholder-shown) {
  color: #828282;
}
```
will be transpiled with autoprefixer without any difference. But if we put another semicolon so it will be looked like pseudo-element
```css
.SiteForm__input:not(::placeholder-shown) {
  color: #828282;
}
```
it will be transpiled to this code 
```css
.SiteForm__input:not(::-webkit-input-placeholder-shown) {
  color: #828282;
}
.SiteForm__input:not(::-moz-placeholder-shown) {
  color: #828282;
}
.SiteForm__input:not(:-ms-input-placeholder-shown) {
  color: #828282;
}
.SiteForm__input:not(::-ms-input-placeholder-shown) {
  color: #828282;
}
.SiteForm__input:not(::placeholder-shown) {
  color: #828282;
}
```
[W3C says](https://drafts.csswg.org/selectors-4/#placeholder) that it's a pseudo-class, so I expected that the first code sample would be transpiled to the last (but with only one colon before placeholder-shown of course). Am I mistaken somewhere?

**Comment by ai** [comment] 2020-09-08 04:05
Seems like it is a bug. We parse `::placeholder-shown` as a `[::placeholder]-shown` and apply `::`placeholder` prefixes.

It will be nice to fix, but I will not have it in the next months.

Do you want to make a contribution to a popular project? The bug came from [`Placeholder` hack](https://github.com/postcss/autoprefixer/blob/master/lib/hacks/placeholder.js) or in [`Selector` abstract class](https://github.com/postcss/autoprefixer/blob/master/lib/selector.js). Very likely because we are using regexps.

**Comment by Semigradsky** [comment] 2020-09-08 08:19
I can't reproduce it on last version (`9.8.6`)

**Comment by Semigradsky** [comment] 2020-09-08 08:32
`:placeholder-shown` hack [was added in `9.8.0` 😄 ](https://github.com/postcss/autoprefixer/blob/master/CHANGELOG.md#98-vigilo-confido)

**Comment by ai** [comment] 2020-09-08 18:10
Great. So we can close it?

**Closed by ai** 2020-09-08 18:10 UTC
Labels: bug
