### ISSUE TITLE
`::file-selector-button` support

### ISSUE THREAD

**Issue by XhmikosR** [postcss/autoprefixer#1374] opened 2020-11-17 20:53 UTC
It seems [`::file-selector-button`](https://caniuse.com/?search=file-selector-button) isn't automatically prefixed using autoprefixer v10.0.2.

Opening the issue as a feature request to add support for it.

Thanks in advance!

**Comment by ai** [comment] 2020-11-17 22:05
Since there is no W3C or W3C draft we consider that there is no `::file-selector-button` selector.

It could be changed and it will be hard to fix it in Autoprefixer.

But I will glad to add it when it will be part of any draft.

**Comment by XhmikosR** [comment] 2020-11-17 22:15
I thought autoprefixer already handles properties that aren't in the spec?

Anyway, I'll see what it needs so that we get this added in the specs.

**Comment by ai** [comment] 2020-11-17 22:17
> I thought autoprefixer already handles properties that aren't in the spec?

Yeah, but they should be at least in a draft.

We had few exceptions, but it led to problems when an unprefixed property name was changed in the spec. So we decided to wait at least until the draft will be ready.

**Comment by XhmikosR** [comment] 2020-11-17 22:32
@ai https://developer.mozilla.org/en-US/docs/Web/CSS/::file-selector-button#Specifications

>The pseudo-element has been resolved on by the CSS WG however the edit has not yet been made in a specification.

Also, as @MikeSmith pointed out:

* https://github.com/mozilla/wg-decisions/issues/323
* https://github.com/web-platform-tests/wpt/commit/1c921cfcc3053cce14b2c23ab38f2dce2710d29f

**Comment by ai** [comment] 2020-11-17 22:43
Yeap, we are waiting for specification edit

**Comment by yisibl** [comment] 2020-12-14 02:55
Firefox https://bugzilla.mozilla.org/show_bug.cgi?id=1662478
https://groups.google.com/a/chromium.org/g/blink-dev/c/d4UdwpPDXJM

![image](https://user-images.githubusercontent.com/2784308/102035204-c881cc00-3dfa-11eb-8c5e-aa0fb873a025.png)

**Comment by XhmikosR** [comment] 2020-12-14 07:43
Actually that doesn't fix what @ai asked. But yesterday they made the PR to add it in the specs here: https://github.com/w3c/csswg-drafts/pull/5788

ai: can you reconsider now please?

**Comment by ai** [comment] 2020-12-14 10:36
I am in Cyberpunk 2077 for the next weeks.

I will review this issue again when I will finish the game.

**Comment by Semigradsky** [comment] 2020-12-30 12:32
https://github.com/Fyrd/caniuse/pull/5722 - my attempt to add `::file-selector-button` info to `caniuse-db`

**Comment by XhmikosR** [comment] 2021-01-13 22:50
@ai friendly ping; I hope you finished Cyberpunk by now (I'm not a gamer myself 😛)

**Comment by ai** [comment] 2021-01-13 23:01
The problem is how we can get data from MDN

**Comment by yisibl** [comment] 2021-01-28 09:13
Safari: https://trac.webkit.org/changeset/270784/webkit/

**Comment by lukewarlow** [comment] 2021-07-09 19:12
> The problem is how we can get data from MDN

MDNs data is available via the `@mdn/browser-compat-data` npm package. Perhaps this could be used for features such as `::file-selector-button` and `:autofill` that aren't available in the caniuse data?

**Comment by ai** [comment] 2021-07-09 20:11
@lukeapage send PR, let’s see what we can do

**Comment by lukewarlow** [comment] 2021-07-09 20:29
I've made a draft PR which shows that it's possible. Idk if you'd be interested in this approach though as it would rely on staying somewhat up to date with the mdn package. Feel free to suggest ways in which I could improve the code. I know it could do with a cleanup and testing of the MDN data processing function.

**Comment by ai** [comment] 2021-07-09 21:08
@lukeapage by the way, do we need this prefix for the modern browsers?

**Comment by lukewarlow** [comment] 2021-07-09 21:38
Idk if you think you're tagging me or not. But to answer your question, all three browser engines support the unprefixed version. However, that only gets us to 78% browser support. To get 95% you would need to prefix. (data from caniuse)

**Comment by ai** [comment] 2021-07-09 22:21
@lukewarlow oops. I tagged wrong person 😅

I think it is not a good idea to add 12 MB dependency or adding MDN data to `caniuse-lite` for this case.

What if we will hardcode browsers versions manually to `data/prefixes.js`?

**Comment by lukewarlow** [comment] 2021-07-09 22:30
Yeah that was going to be my follow up idea. It shouldn't need updating either because we know the exact versions it's added for every browser. I'll update the PR to do this instead.

**Closed** 2021-07-10 10:54 UTC
Labels: support

**Comment by ai** [comment] 2021-07-10 11:16
The fix was released in 10.3.
