### ISSUE TITLE
new version `9.7.1` has problem when prefix `::placeholder`

### ISSUE THREAD

**Issue by aaronkzhou** [postcss/autoprefixer#1263] opened 2019-11-05 22:21 UTC
Hey support team,

Autoprefixing with new version `9.7.1` bump into bug with `::placeholder`.

```
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
TypeError: Cannot read property 'indexOf' of undefined
```

**Comment by ai** [comment] 2019-11-05 22:23
Do you have full stack trace? Or do you have minimal CSS to reproduce the error?

**Comment by aaronkzhou** [comment] 2019-11-05 22:24
update the stack trace
```
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
TypeError: Cannot read property 'indexOf' of undefined
    at /Users/t826148/dev/lightbox/repo/desktop/src/app/layouts/shared-navigation/search-nav-button.css:56:3
    at /Users/t826148/dev/lightbox/repo/desktop/node_modules/postcss-responsive-type/index.js:219:25
    at /Users/t826148/dev/lightbox/repo/desktop/node_modules/postcss/lib/container.js:239:18
    at /Users/t826148/dev/lightbox/repo/desktop/node_modules/postcss/lib/container.js:135:18
    at Root.each (/Users/t826148/dev/lightbox/repo/desktop/node_modules/postcss/lib/container.js:101:16)
    at Root.walk (/Users/t826148/dev/lightbox/repo/desktop/node_modules/postcss/lib/container.js:131:17)
    at Root.walkRules (/Users/t826148/dev/lightbox/repo/desktop/node_modules/postcss/lib/container.js:237:19)
    at /Users/t826148/dev/lightbox/repo/desktop/node_modules/postcss-responsive-type/index.js:213:9
    at LazyResult.run (/Users/t826148/dev/lightbox/repo/desktop/node_modules/postcss/lib/lazy-result.js:295:14)
    at LazyResult.asyncTick (/Users/t826148/dev/lightbox/repo/desktop/node_modules/postcss/lib/lazy-result.js:208:26)
    at LazyResult.asyncTick (/Users/t826148/dev/lightbox/repo/desktop/node_modules/postcss/lib/lazy-result.js:221:14)
    at LazyResult.asyncTick (/Users/t826148/dev/lightbox/repo/desktop/node_modules/postcss/lib/lazy-result.js:221:14)
    at /Users/t826148/dev/lightbox/repo/desktop/node_modules/postcss/lib/lazy-result.js:213:17
    at runLoaders (/Users/t826148/dev/lightbox/repo/desktop/node_modules/webpack/lib/NormalModule.js:316:20)
    at /Users/t826148/dev/lightbox/repo/desktop/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/t826148/dev/lightbox/repo/desktop/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/t826148/dev/lightbox/repo/desktop/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Promise.resolve.then.then.catch (/Users/t826148/dev/lightbox/repo/desktop/node_modules/postcss-loader/src/index.js:208:9)
```

**Comment by aaronkzhou** [comment] 2019-11-05 22:25
and here is minimum css
```
.searchInput {
  background-image: url('../../../images/search.svg');
  background-repeat: no-repeat;
  background-position: right 50%;
  background-size: 20px 20px;
  background-color: transparent;
  border: 0;
  caret-color: #777;
  color: var(--white);
  cursor: pointer;
  font-family: "GothamRounded";
  font-size: 0;
  height: 28px;
  outline: none;
  width: 24px;
  transition: width 0.25s;
  display: flex;
  padding-left: 26px;

  &::placeholder {
    color: var(--white);
    opacity: 1;
  }
}
```

**Comment by ai** [comment] 2019-11-05 22:27
Seems like the error came from `postcss-responsive-type` plugin. Can you create an issue there and mention me there.

It seems like Autoprefixer release change AST a little and it opens an old error in `postcss-responsive-type`.

I am closing the issue since there is no Autoprefixer in stack trace. I will reopen it if we will find that Autopefixer breaks AST.

**Closed by ai** 2019-11-05 22:27 UTC

**Comment by Kyoloro** [comment] 2019-11-29 04:05
same behavior

**Comment by Kyoloro** [comment] 2019-11-29 04:20
autoprefixer@9.6.0 works fine
autoprefixer@9.7.2 emit error: selector length

**Comment by ai** [comment] 2019-11-29 08:41
> autoprefixer@9.7.2 emit error: selector length

Show the full stacktrace and error message
