### ISSUE TITLE
[css-grid]min-content/max-content prefix in Safari

### ISSUE THREAD

**Issue by yisibl** [postcss/autoprefixer#803] opened 2017-03-15 14:00 UTC
input:

```css
.foo {
     grid-template-columns: minmax(100px, min-content);
}
```

output:

```css
.foo {
     -ms-grid-columns: minmax(100px, min-content);
         grid-template-columns: minmax(100px, min-content);
}
```

These properties just remove the prefix in https://trac.webkit.org/changeset/213831 , but I'm not sure which version of Safari.

@mrego Can you help me?

http://caniuse.com/#feat=css-grid

**Comment by mrego** [comment] 2017-03-15 14:04
Apple doesn't publicly talk about their Safari releases, so we don't know.
I don't think it would be part of 10.1 as the beta has been around for a while, so probably Safari 11 or 10.2 if that ever exists.
Sorry for not being really helpful, you'd need to wait and check when it's or not included.

**Comment by ai** [comment] 2017-03-15 15:52
@yisibl what is expected output?

**Comment by yisibl** [comment] 2017-03-16 02:43
@mrego Well, it looks like caniuse's data is inaccurate.

@ai Maybe we don't need a prefix in `minmax(100px, -webkit-min-content)`,We have to wait for Safari to officially support Grid.

**Comment by ai** [comment] 2017-03-16 06:05
@yisibl ouh, I will add grid properties to `min-content` https://github.com/postcss/autoprefixer/blob/master/data/prefixes.coffee#L292

Do you want to make PR to save your name in history (again)? :)

**Comment by mrego** [comment] 2017-03-16 08:21
One special thing here, `fit-content` cannot be prefixed inside grid properties, or it won't work. I know it's a weird situation but that's how things are right now.
So valid declarations would be:
```grid-template-columns: -webkit-min-content -webkit-max-content fit-content(500px);```
However the following one would be invalid:
```grid-template-columns: -webkit-min-content -webkit-max-content -webkit-fit-content(500px);```

Note that `fit-content` in the grid properties is not a keyword like `min|max-content` but a kind of "function". That's the reason why it was implemented as something new and unprefixed since the beginning.

**Comment by yisibl** [comment] 2017-03-16 12:52
@mrego OK, I see, `fit-content()` no prefix.

@ai  Yeah, willing to serve you 👻 .

**Comment by yisibl** [comment] 2017-03-17 05:18
Safari 10.1 shipped: https://developer.apple.com/library/prerelease/content/releasenotes/General/WhatsNewInSafari/Articles/Safari_10_1.html#//apple_ref/doc/uid/TP40014305-CH12-DontLinkElementID_55

**Comment by yisibl** [comment] 2017-03-21 12:51
Add test case: https://github.com/postcss/autoprefixer/pull/805

**Comment by ai** [comment] 2017-03-21 12:53
Issue with test pull request — ideal issue :+1: 

Thanks, it will help me a lot.

**Comment by ai** [comment] 2017-05-12 22:07
Done 99def37

**Comment by ai** [comment] 2017-05-15 00:03
Released in 7.1

**Comment by jayenashar** [comment] 2018-01-06 06:27
Hi I've got a related issue where:

    grid-template: max-content 1fr max-content max-content / max-content 1fr;

is getting prefixed as:

    grid-template: -webkit-max-content 1fr -webkit-max-content max-content / -webkit-max-content 1fr;

I expect that to be:

    grid-template: -webkit-max-content 1fr -webkit-max-content -webkit-max-content / -webkit-max-content 1fr;

that is, `-webkit-` is missing from the third `max-content`, but not the first, second, or fourth...

**Comment by ai** [comment] 2018-01-06 06:29
@jayenashar confirmed. I will try to fix it on next week.

**Comment by jayenashar** [comment] 2018-01-06 06:29
that was FAST

**Comment by ai** [comment] 2018-01-12 12:12
@jayenashar fixed ecd7eed

**Comment by ai** [comment] 2018-01-12 12:31
@jayenashar released in 7.2.5.

**Comment by jayenashar** [comment] 2018-01-13 00:13
thanks!

**Closed** 2018-02-11 20:40 UTC
