### ISSUE TITLE
caniuse-lite 1.0.30000888 - 9/28/2018 IE placeholder broken

### ISSUE THREAD

**Issue by tkrotoff** [postcss/autoprefixer#1134] opened 2018-09-30 18:11 UTC
Latest caniuse-lite version (1.0.30000888 - 9/28/2018) breaks IE placeholder: https://github.com/ben-eb/caniuse-lite/issues/16

So autoprefixer won't generate for IE 10/11:
```CSS
input:-ms-input-placeholder {
  ...
}
```

I suggest to temporary specify `"caniuse-lite": "1.0.30000887"` inside package.json (instead of `"caniuse-lite": "^1.0.30000884"`) so other devs won't be bitten by this bug (took me quite some time to found the culprit).

Meanwhile in my `package.json` I've specified
```JSON
"resolutions": {
  "caniuse-lite": "1.0.30000887"
}
```
thanks to Yarn' [selective dependency resolutions](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/).

**Comment by Dan503** [comment] 2018-09-30 21:01
Specifying a hard version number like that in a library is a bad idea. It would mean that every time `caniuse-lite` updates itself, Autoprefixer would need to publish a new release to use the up to date version. If there is something like a security patch update, we want Autoprefixer to be able to receive that patch automatically.

This is a bug with caniuse-lite. Unfortunately it is best if we just wait until the issue is fixed on their end.

**Comment by tkrotoff** [comment] 2018-09-30 21:32
> Autoprefixer would need to publish a new release to use the up to date version

Forgot to precise: hard version number should be temporary. Once caniuse-lite is fixed then rollback to `^`.

**Comment by ai** [comment] 2018-09-30 23:15
Did somebody send a PR to `caniuse-db`?

**Comment by ai** [comment] 2018-10-03 10:33
Issue in `caniuse-db`: https://github.com/Fyrd/caniuse/issues/4095

**Comment by ai** [comment] 2018-10-03 10:33
It should be fixed since PR was merged

**Comment by ai** [comment] 2018-10-03 10:34
@tkrotoff can you test it again?

**Closed** 2018-10-12 16:20 UTC
Labels: bug

**Comment by ai** [comment] 2018-10-14 04:28
Issue will be fixed in 9.2 7090ae3

**Comment by Blacknikomo** [comment] 2018-10-17 11:33
The issue still exists within the caniuse-lite@1.0.30000892

**Comment by tkrotoff** [comment] 2018-11-03 14:53
I confirm the issue has been fixed. Thx!

**Comment by aleen42** [comment] 2020-01-20 08:44
I have tested 9.7.4 but it seemed that the bug was still existed

**Comment by ai** [comment] 2020-01-20 08:49
@aleen42 try to update `caniuse-lite` in `node_modules`. You can check that all packages use the latest versions by `npm ls | grep caniuse-lite`

**Comment by aleen42** [comment] 2020-01-21 05:38
I had a wrong test, and it worked.
